### ISSUE TITLE
[BUG] "@micro-sentry/core" peer dependency in "@micro-sentry/angular" package

### ISSUE THREAD

**Issue by hakimio** [TinkoffCreditSystems/micro-sentry#1]
# 🐞 Bug report

### Description

Since `@micro-sentry/core` is peer dependency instead of "hard" dependency, user has to install it explicitly.
Either installation instructions should be updated or `@micro-sentry/core` should be upgraded to "hard" dependency.

![sentry core](https://user-images.githubusercontent.com/768105/122224886-d6510080-ceb4-11eb-81eb-99136367d03f.PNG)

**Comment by MarsiBarsi** [comment]
Hey Tomas 👋
Thank you very much for your issue! Interesting...

So, the angular package has a "hard" dependency to `@micro-sentry/browser` that uses `@micro-sentry/core` inside. But it does not use `@micro-sentry/core` directly at all and it is not in [its peer deps](https://github.com/TinkoffCreditSystems/micro-sentry/blob/main/libs/angular/package.json#L4). @IKatsuba take a look, please, it seems that something (nx? builders?) adds extra peer dependency while building

**Comment by hakimio** [comment]
@MarsiBarsi 
`@micro-sentry/browser` hard dependency in your `@micro-sentry/angular` library doesn't make any sense as well. The latest `@micro-sentry/browser` version is `2.0.0` while your `@micro-sentry/angular` depends on v0.xx:
```json
  "dependencies": {
    "tslib": "^2.1.0",
    "@micro-sentry/browser": "^0.0.1"
  }
```

**Comment by MarsiBarsi** [comment]
We have a custom semrel angular builder here that should solve this case automatically but something went wrong :( Igor will check the builder and one of us will check the problem about added peer soon
